### ISSUE TITLE
Need to consider earthing to the capacitive sensors.

### ISSUE THREAD

**Issue by nadavfedida** [Kushan-Nilanga/SIT329-Project#26]
This issue is to discuss how to tacking the earthing potential issue. 

We need to taking into account if the bike needs to be earthed to the same potential as the FPGA, which in that case, thee user will be grounded to the bike. 

The diagram below shows that we might need to be grounded.

![Image](https://user-images.githubusercontent.com/62866537/188263808-f256f7aa-f28a-4bfd-8501-9d4b5b678647.png)

However, as Adrian was mentioning, in his testing he was still able to get decent results whilst not "grounded"

**Comment by SachiniWitharana** [comment]
I believe that this could be tested, as in we could compare the values, we could then determine if we need to take into account if the bike needs to be earthed to the same potential as the FPGA.

**Comment by nadavfedida** [comment]
We certainly can. Once we have a working version of the capacitive sensor going, whom ever has it should test this and update the rest of us on the findings. 

I believe it won't make a difference if the bike is earthed to the same potential as the FPGA ground, but we shall wait and see.

**Comment by Kushan-Nilanga** [comment]
After the implementation of the sensors, we identified that the grounding of the capacitor provides stability to the sensor readings. It has been evident throughout the initial testing that capacitors and grounding provide stability and reliability on sensor data. However, implementation of the sensors allows them to be used as both Grounded and Ungrounded mode
